Release 5.1
uniformdev/optimize-sitecore-jss-nextjs-starterkit pull request #3
Opened 2021-09-22 11:27 UTC by AlenPelin

2021-09-22 11:31 UTC, AlenPelin commented
@alexshyba for some reason I cannot assign you as a reviewer on this like I did with others

2021-09-22 21:40 UTC, alexshyba requested changes

2021-09-22 21:40 UTC, alexshyba commented on uniform.config.js
> +  UNIFORM_API_KEY: 'eefe326b-aff1-4154-9ae8-2beb85d4b8cb',
@AlenPelin ?

2021-09-22 21:40 UTC, alexshyba commented on cloudflare-worker/wrangler-webpack.config.js
> +//const path = require('path')
@AlenPelin dead code

2021-09-23 06:04 UTC, AlenPelin commented on cloudflare-worker/wrangler-webpack.config.js
> +//const path = require('path')
not a release blocker

2021-09-23 06:44 UTC, closed without merging